export { default as Header } from './Header/Header'
export { default as About } from './About/About'
export { default as Services } from './Services/Services'
export { default as Contact } from './Contact/Contact'
export { default as Workout } from './Workout/Workout'
export { default as Blog } from './Blog/Blog'
export { default as Reviews } from './Reviews/Reviews'
export { default as Footer } from './Footer/Footer'