const ExerciseList = [
  [
    [
      'press up 15 reps',
      'clean and press 15 reps',
      'dips 10 reps',
      'back rows 15 reps',
      'laterals 15 reps',
      'overhead presses 15 reps',
      'curls 15 reps',
      'tricep extensions 20 reps',
      'upright rows 15 reps',
      'front raises 15 reps',
      'reverse fly 20 reps',
      'renegade rows 10 reps each arm',
      'chest flye 20 reps'
    ],
    [
      'squats 30 reps',
      'crucifix squat 20 reps',
      'lunges 30 reps',
      'push press 20 reps',
      'raised bridges 30 reps',
      'pulse squats 20 reps',
      'reverse lunges 30 reps',
      'jump squats 20 reps',
      'bridges 50 reps',
      'split squats 30 reps',
      'deadlifts 20 reps',
      'side lunges 30 reps',
      'bulgarian split squats 30 reps',
      'wide squats 30 reps',
      'jump lunges 20 reps',
      'curtsey lunges 30 reps',
      'bear squats 30 reps',
      'knee up 30 reps',
      'wall sit 1 min',
      'cossack squats 30 reps'
    ],
    [
      'crunches 25 reps',
      'plank 1 min',
      'side plank 30 sec each side',
      'jacknifes 20 reps',
      'deadbugs 20 reps',
      'bicycle crunches 30 reps',
      'reverse crunches 20 reps',
      'plank reach 20 reps',
      'hollow hold 45 sec',
      'woodchop 15 each side',
      'russian twist 30 reps',
      'plank taps 30 reps'
    ],
    [
      'mountain climbers 30 sec',
      'cross climbers 30 sec',
      'jump jacks 45 reps',
      'squat jacks 25 reps',
      'plank jacks 30 reps',
      'high knees 40 sec',
      'fast feet 40 sec',
      'walkouts 15 reps',
      'bear crawls 5m 5 reps',
      'burpees 20 reps',
      'froggers 20 reps'
    ]
  ],

  [
    [
      'squats 30 reps',
      'crucifix squat 20 reps',
      'lunges 30 reps',
      'push press 20 reps',
      'raised bridges 30 reps',
      'pulse squats 20 reps',
      'reverse lunges 30 reps',
      'jump squats 20 reps',
      'bridges 50 reps',
      'split squats 30 reps',
      'deadlifts 20 reps',
      'side lunges 30 reps',
      'bulgarian split squats 30 reps',
      'wide squats 30 reps',
      'jump lunges 20 reps',
      'curtsey lunges 30 reps',
      'bear squats 30 reps',
      'knee up 30 reps',
      'wall sit 1 min',
      'cossack squats 30 reps'
    ],
    [
      'press up 15 reps',
      'clean and press 15 reps',
      'dips 10 reps',
      'back rows 15 reps',
      'laterals 15 reps',
      'overhead presses 15 reps',
      'curls 15 reps',
      'tricep extensions 20 reps',
      'upright rows 15 reps',
      'front raises 15 reps',
      'reverse fly 20 reps',
      'renegade rows 10 reps each arm',
      'chest flye 20 reps'
    ],
    [
      'squats 30 reps',
      'crucifix squat 20 reps',
      'lunges 30 reps',
      'push press 20 reps',
      'raised bridges 30 reps',
      'pulse squats 20 reps',
      'reverse lunges 30 reps',
      'jump squats 20 reps',
      'bridges 50 reps',
      'split squats 30 reps',
      'deadlifts 20 reps',
      'side lunges 30 reps',
      'bulgarian split squats 30 reps',
      'wide squats 30 reps',
      'jump lunges 20 reps',
      'curtsey lunges 30 reps',
      'bear squats 30 reps',
      'knee up 30 reps',
      'wall sit 1 min',
      'cossack squats 30 reps'
    ],
    [
      'crunches 25 reps',
      'plank 1 min',
      'side plank 30 sec each side',
      'jacknifes 20 reps',
      'deadbugs 20 reps',
      'bicycle crunches 30 reps',
      'reverse crunches 20 reps',
      'plank reach 20 reps',
      'hollow hold 45 sec',
      'woodchop 15 each side',
      'russian twist 30 reps',
      'plank taps 30 reps'
    ],
    [
      'mountain climbers 30 sec',
      'cross climbers 30 sec',
      'jump jacks 45 reps',
      'squat jacks 25 reps',
      'plank jacks 30 reps',
      'high knees 40 sec',
      'fast feet 40 sec',
      'walkouts 15 reps',
      'bear crawls 5m 5 reps',
      'burpees 20 reps',
      'froggers 20 reps'
    ]
  ],

  [
    [
      'squats 30 reps',
      'crucifix squat 20 reps',
      'lunges 30 reps',
      'push press 20 reps',
      'raised bridges 30 reps',
      'pulse squats 20 reps',
      'reverse lunges 30 reps',
      'jump squats 20 reps',
      'bridges 50 reps',
      'split squats 30 reps',
      'deadlifts 20 reps',
      'side lunges 30 reps',
      'bulgarian split squats 30 reps',
      'wide squats 30 reps',
      'jump lunges 20 reps',
      'curtsey lunges 30 reps',
      'bear squats 30 reps',
      'knee up 30 reps',
      'wall sit 1 min',
      'cossack squats 30 reps'
    ],
    [
      'press up 15 reps',
      'clean and press 15 reps',
      'dips 10 reps',
      'back rows 15 reps',
      'laterals 15 reps',
      'overhead presses 15 reps',
      'curls 15 reps',
      'tricep extensions 20 reps',
      'upright rows 15 reps',
      'front raises 15 reps',
      'reverse fly 20 reps',
      'renegade rows 10 reps each arm',
      'chest flye 20 reps'
    ],
    [
      'squats 30 reps',
      'crucifix squat 20 reps',
      'lunges 30 reps',
      'push press 20 reps',
      'raised bridges 30 reps',
      'pulse squats 20 reps',
      'reverse lunges 30 reps',
      'jump squats 20 reps',
      'bridges 50 reps',
      'split squats 30 reps',
      'deadlifts 20 reps',
      'side lunges 30 reps',
      'bulgarian split squats 30 reps',
      'wide squats 30 reps',
      'jump lunges 20 reps',
      'curtsey lunges 30 reps',
      'bear squats 30 reps',
      'knee up 30 reps',
      'wall sit 1 min',
      'cossack squats 30 reps'
    ],
    [
      'squats 30 reps',
      'crucifix squat 20 reps',
      'lunges 30 reps',
      'raised bridges 30 reps',
      'pulse squats 20 reps',
      'reverse lunges 30 reps',
      'jump squats 20 reps',
      'bridges 50 reps',
      'split squats 30 reps',
      'deadlifts 20 reps',
      'side lunges 30 reps',
      'bulgarian split squats 30 reps',
      'wide squats 30 reps',
      'jump lunges 20 reps',
      'curtsey lunges 30 reps',
      'bear squats 30 reps',
      'knee up 30 reps',
      'wall sit 1 min',
      'cossack squats 30 reps'
    ],
    [
      'crunches 25 reps',
      'plank 1 min',
      'side plank 30 sec each side',
      'jacknifes 20 reps',
      'deadbugs 20 reps',
      'bicycle crunches 30 reps',
      'reverse crunches 20 reps',
      'plank reach 20 reps',
      'hollow hold 45 sec',
      'woodchop 15 each side',
      'russian twist 30 reps',
      'plank taps 30 reps'
    ],
    [
      'mountain climbers 30 sec',
      'cross climbers 30 sec',
      'jump jacks 45 reps',
      'squat jacks 25 reps',
      'plank jacks 30 reps',
      'high knees 40 sec',
      'fast feet 40 sec',
      'walkouts 15 reps',
      'bear crawls 5m 5 reps',
      'burpees 20 reps',
      'froggers 20 reps'
    ]
  ]
]

export default ExerciseList
